version: "3.9"

services:
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    command: >
      sh -c "/py/bin/python manage.py migrate &&
            gunicorn app.wsgi:application --bind 0.0.0.0:8000 --workers 3"
    env_file:
      - .env
    depends_on:
      - db
    user: "1000:1000"  #no seria recomendado usar root como en el local, pero chequearlo con fede por las dudas. ver tema permisos

  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  postgres_data:


# no estoy montando el volumen aca como en dev, ./app:/app se supone que esta en la imagen pero no se como chequearlo
# migraciones ejecutarlas a mano? crear script?