version: "3.9"

services:
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app #ojo en prod
    command: >
      sh -c "/py/bin/python manage.py migrate &&
            /py/bin/python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    depends_on:
      - db
    user: root #ojo con esto en prod

  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  postgres_data:


#revisar los commands para prod, y las migraciones como se hacen? a mano? o puedo dejar el comando migrate?